CREATE TABLE IF NOT EXISTS users
(
    id    int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar(100)        NOT NULL,
    email varchar(100) UNIQUE NOT NULL
);


CREATE TABLE IF NOT EXISTS requests
(
    id            int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description   text,
    requester_id  int8      NOT NULL,
    creation_date timestamp NOT NULL,
    CONSTRAINT fk_on_requester FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items
(
    id           int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(100) NOT NULL,
    description  text         NOT NULL,
    is_available bool         NOT NULL,
    owner_id     int8         NOT NULL,
    request_id   int8,
    CONSTRAINT items_fk_on_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT items_fk_on_request FOREIGN KEY (request_id) REFERENCES requests (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS bookings
(
    id             int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date     timestamp   NOT NULL,
    end_date       timestamp   NOT NULL,
    item_id        int8        NOT NULL,
    booker_id      int8        NOT NULL,
    booking_status varchar(20) NOT NULL,
    CONSTRAINT bookings_fk_on_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    CONSTRAINT bookings_fk_on_booker FOREIGN KEY (booker_id) REFERENCES users (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS comments
(
    id            int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text          text      NOT NULL,
    item_id       int8      NOT NULL,
    author_id     int8      NOT NULL,
    creation_time timestamp NOT NULL,
    CONSTRAINT comments_fk_on_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    CONSTRAINT comments_fk_on_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE

);