CREATE TABLE IF NOT EXISTS users
(
    id    int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar(100)        NOT NULL,
    email varchar(100) UNIQUE NOT NULL
);


CREATE TABLE IF NOT EXISTS requests
(
    id           int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description  text,
    requester_id int8 REFERENCES users (id) NOT NULL
);

CREATE TABLE IF NOT EXISTS items
(
    id           int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(100) NOT NULL,
    description  text         NOT NULL,
    is_available bool         NOT NULL,
    owner_id     int8 REFERENCES users (id),
    request_id   int8 REFERENCES requests (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date timestamp                  NOT NULL,
    end_date   timestamp                  NOT NULL,
    item_id    int8 REFERENCES items (id) NOT NULL,
    booker_id  int8 REFERENCES users (id) NOT NULL,
    booking_status     varchar(20)                NOT NULL
);


CREATE TABLE IF NOT EXISTS comments
(
    id        int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      text                       NOT NULL,
    item_id   int8 REFERENCES items (id) NOT NULL,
    author_id int8 REFERENCES users (id) NOT NULL,
    creation_time timestamp NOT NULL
);